# Delete Git branch of closed Pull Requests

on:
  workflow_call:
    inputs:
      dry-run:
        description: "Simulate (dry-run) operation - Default: true"
        required: false
        type: boolean
        default: true

permissions:
  contents: write

jobs:
  delete_branch:
    runs-on: ubuntu-latest
    if: ${{ github.head_ref }}
    steps:
    - id: git_checkout
      uses: actions/checkout@v4

    - id: git_delete_branch_if_exists
      if: ${{ ! inputs.dry-run }}
      run: |
        if git fetch origin ${{ github.head_ref }}; then
          git push -d origin ${{ github.head_ref }}
        fi

# EoF
