name: Delete Git branch of closed Pull Requests

on:
  workflow_call:
    inputs:
      dry-run:
        description: "Simulate (dry-run) operation - Default: true"
        required: false
        type: boolean
        default: true

permissions:
  contents: write

jobs:
  delete_branch:
    runs-on: ubuntu-latest
    if: ${{ github.head_ref }}
    steps:
    - uses: actions/checkout@v4

    - if: ${{ ! inputs.dry-run }}
      name: (simulate=$${ inputs.dry-run }}) git push -d origin ${{ github.head_ref }}
      run: git push -d origin ${{ github.head_ref }}

